# ДЗ 4. Задание 1

In [25]:
import numpy as np
import pandas as pd

In [26]:
def tablichka(a):
    """
    это чтобы матрицы выглядели красивенько
    """
    df = pd.DataFrame(a, index=['A', 'T', 'G', 'C'])
    return df

In [27]:
sites = ["GAGGTAAAC", "TCCGTAAGC", "CAGGTTGGA",
"ACAGTCAGC", "TAGGTCAGC", "CAGGTCAGC",
"CAGGTCGAT", "CAGGTCAGC", "CAGGTCAGC",
"CAGGTTGGC"]

## PFM

In [28]:
pfm = np.zeros(shape=(4,len(sites[0])))
for site in sites:
    site = list(site)
    for j in range(len(site)):
        if site[j]=='A':
            pfm[0,j]+=1
        if site[j]=='T':
            pfm[1,j]+=1
        if site[j]=='G':
            pfm[2,j]+=1
        if site[j]=='C':
            pfm[3,j]+=1

In [29]:
tablichka(pfm)

     0    1    2     3     4    5    6    7    8
A  1.0  8.0  1.0   0.0   0.0  2.0  7.0  2.0  1.0
T  2.0  0.0  0.0   0.0  10.0  2.0  0.0  0.0  1.0
G  1.0  0.0  8.0  10.0   0.0  0.0  3.0  8.0  0.0
C  6.0  2.0  1.0   0.0   0.0  6.0  0.0  0.0  8.0

## PPM

In [30]:
m = pfm + 0.1
ppm = m / np.sum(m, axis=0)
tablichka(ppm)

,0,1,2,3,4,5,6,7,8
A,0.105769,0.778846,0.105769,0.009615,0.009615,0.201923,0.682692,0.201923,0.105769
T,0.201923,0.009615,0.009615,0.009615,0.971154,0.201923,0.009615,0.009615,0.105769
G,0.105769,0.009615,0.778846,0.971154,0.009615,0.009615,0.298077,0.778846,0.009615
C,0.586538,0.201923,0.105769,0.009615,0.009615,0.586538,0.009615,0.009615,0.778846

## PWM

In [31]:
ppm_AT = np.log2(ppm[0:2] / 0.295)
ppm_GC = np.log2(ppm[2:4] / 0.205)

pwm = np.vstack((ppm_AT, ppm_GC))
tablichka(pwm)

,0,1,2,3,4,5,6,7,8
A,-1.479795,1.400623,-1.479795,-4.939227,-4.939227,-0.546909,1.210521,-0.546909,-1.479795
T,-0.546909,-4.939227,-4.939227,-4.939227,1.718985,-0.546909,-4.939227,-4.939227,-1.479795
G,-0.954704,-4.414136,1.925714,2.244076,-4.414136,-4.414136,0.540061,1.925714,-4.414136
C,1.516602,-0.021818,-0.954704,-4.414136,-4.414136,1.516602,-4.414136,-4.414136,1.925714

## Максимальный и минимальный скор

In [32]:
max_scores = np.max(pwm, axis=0)
min_scores = np.min(pwm, axis=0)
max_indices = np.argmax(pwm, axis=0)
min_indices = np.argmin(pwm, axis=0)

max_score = np.sum(max_scores)
min_score = np.sum(min_scores)

In [33]:
nucl = ['A', 'T', 'G', 'C']
max_sequence = ''
min_sequence = ''
for i in max_indices:
    max_sequence += nucl[i]
for i in min_indices:
    min_sequence += nucl[i]

In [34]:
print(f'Максмальный скор: {max_score}, последовательносьть: {max_sequence}')
print(f'Минимальный скор: {min_score}, последовательносьть: {min_sequence}')

Максмальный скор: 15.384551840581208, последовательносьть: CAGGTCAGC
Минимальный скор: -39.94342549142906, последовательносьть: ATTAAGTTG